### ISSUE TITLE
Leaked discord BOT token

### ISSUE THREAD

**Issue by FlowingSPDG** [B3none/old-csgo-league-bot#1]
https://github.com/csgo-league/csgo-league-bot/blob/78677f8a34bde3d2a199c90b74785f03cab29f4b/config.json#L2
You should probably re-generate token XD

**Comment by B3none** [comment]
Shit, yeah, might help lmfao. It's not used anywhere afaik

**Comment by FlowingSPDG** [comment]
yupp im not gonna abuse it for sure,but probably replace with random string like :
`THIS_IS_YOUR_DISCORD_TOKEN` or s.th like that

**Comment by B3none** [comment]
I swapped it out with an empty string and deleted the bot that it's linked to, thanks!
